Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "h1" do |h1|
    h1.vm.network "private_network", ip: "192.20.20.11"
    h1.vm.provision :docker do |d|
      d.pull_images "crosbymichael/redis"
      d.pull_images "svendowideit/ambassador"
    end
  end

  config.vm.define "h2" do |h2|
    h2.vm.network "private_network", ip: "192.20.20.55"
    h2.vm.provision :docker do |d|
      d.pull_images "relateiq/redis-cli"
      d.pull_images "svendowideit/ambassador"
    end
  end
end
