Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "h1" do |h1|
    h1.vm.network "private_network", ip: "192.20.20.11"
    h1.vm.provision :docker do |d|
      d.pull_images "crosbymichael/redis"
    end
  end

  config.vm.define "h2" do |h2|
    h2.vm.network "private_network", ip: "192.20.20.55"
    h2.vm.provision :docker do |d|
      d.pull_images "relateiq/redis-cli"
    end
  end

  config.vm.provision :shell, :inline => <<-EOF
mkdir /usr/local/bin
wget -O /usr/local/bin/weave https://raw.githubusercontent.com/zettio/weave/master/weave
chmod a+x /usr/local/bin/weave
echo "export PATH=$PATH:/usr/local/bin" > /home/vagrant/.bashrc
EOF
  
end
